import datetime
import json
import os
import base64
import mimetypes
import io
import requests
import logging
import re
import textwrap

from jinja2 import Environment, FileSystemLoader
from pypdf import PdfReader, PdfWriter
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm

from company_config import BANK_DETAILS, COMPANY_ADDRESSES, TERMS_AND_CONDITIONS, REQUIRED_DOCUMENTS

# Configure a logger for this module
pdf_generator_logger = logging.getLogger(__name__)
if not pdf_generator_logger.handlers:
    pdf_generator_logger.setLevel(logging.INFO)
    file_handler = logging.FileHandler('pdf_error.log')
    formatter = logging.Formatter('[%(asctime)s] %(levelname)s - %(message)s')
    file_handler.setFormatter(formatter)
    pdf_generator_logger.addHandler(file_handler)

# Configuration
TEMPLATE_DIR = "."
EXPORT_DIR = "./Export"
GOTENBERG_API_URL = "http://localhost:3000/forms/chromium/convert/html"

def generate_pdf_from_data(quote_data):
    """
    Main function to generate a PDF using a multi-pass stamping process.
    """
    try:
        # 1. Prepare common data for all templates
        prepared_data = _prepare_template_data(quote_data)

        # 2. Render HTML for each part
        header_html = _render_html_template(prepared_data, "header.html")
        footer_html = _render_html_template(prepared_data, "footer.html")
        
        pdf_generator_logger.info("--- DEBUG: CONTEXT FOR main_content.html ---")
        pdf_generator_logger.info(f"doc_type: {prepared_data.get('type')}")
        pdf_generator_logger.info(f"service_line_items: {prepared_data.get('service_line_items')}")
        pdf_generator_logger.info("------------------------------------------")
        
        main_html = _render_html_template(prepared_data, "main_content.html")

        # 3. Convert each HTML to a PDF in memory
        header_pdf_bytes = _convert_html_to_pdf(header_html)
        footer_pdf_bytes = _convert_html_to_pdf(footer_html)
        main_pdf_bytes = _convert_html_to_pdf(main_html)

        if not all([header_pdf_bytes, footer_pdf_bytes, main_pdf_bytes]):
            pdf_generator_logger.error("A component PDF could not be generated by Gotenberg.")
            return None

        # 4. Merge and stamp PDFs
        final_pdf_bytes = _stamp_and_paginate(
            main_pdf_bytes,
            header_pdf_bytes,
            footer_pdf_bytes
        )

        # 5. Save the final PDF
        return _save_pdf(final_pdf_bytes, prepared_data.get('doc_no', 'quotation'))

    except Exception as e:
        pdf_generator_logger.error(f"An exception occurred in generate_pdf_from_data: {e}", exc_info=True)
        return None


def _prepare_template_data(quote_data):
    """Enriches the quote data with details needed for rendering."""
    doc_type = quote_data.get("type", "sales")
    
    titles = { "refurbish": "REFURBISH QUOTATION", "rental": "RENTAL QUOTATION", "sales": "SALES QUOTATION" }
    quote_data["document_title"] = titles.get(doc_type, "SALES QUOTATION")

    issuing_company_details = COMPANY_ADDRESSES.get(quote_data.get("issuing_company"), {})
    quote_data["issuing_company_address"] = issuing_company_details.get("address", "N/A")
    quote_data["issuing_company_ssm_no"] = issuing_company_details.get("ssm_no", "")

    logo_path = issuing_company_details.get("logo_path")
    if logo_path and os.path.exists(logo_path):
        try:
            with open(logo_path, "rb") as image_file:
                encoded_string = base64.b64encode(image_file.read()).decode()
            mimetype = mimetypes.guess_type(logo_path)[0] or 'image/png'
            quote_data["issuing_company_logo"] = f"data:{mimetype};base64,{encoded_string}"
        except Exception as e:
            pdf_generator_logger.error(f"Error processing logo file: {e}", exc_info=True)
            quote_data["issuing_company_logo"] = None
    else:
        quote_data["issuing_company_logo"] = None

    quote_data["bank_details"] = BANK_DETAILS.get(quote_data.get("issuing_company"), "N/A")
    quote_data["terms_and_conditions"] = TERMS_AND_CONDITIONS.get(doc_type, TERMS_AND_CONDITIONS.get("sales"))
    quote_data["required_documents"] = REQUIRED_DOCUMENTS.get(doc_type, [])
    quote_data["date"] = datetime.date.today().strftime("%d-%m-%Y")

    # --- Programmatically build all HTML content to be injected ---
    
    # --- Services Provided Box ---
    services_html = ""
    if doc_type == 'sales' and quote_data.get('service_line_items'):
        services_to_display = quote_data['service_line_items']
        
        half_point = (len(services_to_display) + 1) // 2
        left_col = services_to_display[:half_point]
        right_col = services_to_display[half_point:]

        if services_to_display:
            services_html += '<h4 style="margin-top: 20px; margin-bottom: 5px;">Services Provided</h4>'
            services_html += '<table style="width: 100%; border: 0;"><tr style="vertical-align: top;">'
            
            # Left Column
            left_col_html = ""
            for item in left_col:
                desc = item.get('line_description', '')
                match = re.search(r"^(.*?)\s\((.*)\)$", desc)
                if match:
                    desc = match.group(1)
                left_col_html += f'<div class="details-box" style="margin-top: 5px; padding: 5px 10px;"><table style="width: 100%; border: 0;"><tr><td style="border:0; padding: 2px;">{desc}</td><td style="border:0; padding: 2px; text-align: right;">RM {item.get("unit_price", 0.0):,.2f}</td></tr></table></div>'
            services_html += f'<td style="width: 50%; padding-right: 5px; border: 0;">{left_col_html}</td>'

            # Right Column
            right_col_html = ""
            for item in right_col:
                desc = item.get('line_description', '')
                match = re.search(r"^(.*?)\s\((.*)\)$", desc)
                if match:
                    desc = match.group(1)
                right_col_html += f'<div class="details-box" style="margin-top: 5px; padding: 5px 10px;"><table style="width: 100%; border: 0;"><tr><td style="border:0; padding: 2px;">{desc}</td><td style="border:0; padding: 2px; text-align: right;">RM {item.get("unit_price", 0.0):,.2f}</td></tr></table></div>'
            services_html += f'<td style="width: 50%; padding-left: 5px; border: 0;">{right_col_html}</td>'
            
            services_html += '</tr></table>'
            
    quote_data['services_provided_html'] = services_html

    # --- Main Items Table ---
    main_items_html = ""
    if doc_type == 'rental':
        if quote_data.get('main_rental_item'):
            item = quote_data['main_rental_item']
            main_items_html += f'<tr><td style="font-size: 120%;">1</td><td style="font-size: 120%;">{item.get("line_description", "")}</td><td style="font-size: 120%; text-align: right;">1</td><td style="font-size: 120%; text-align: right;">{item.get("unit_price", 0.0):,.2f}</td></tr>'
        if quote_data.get('service_line_items'):
            start_index = 2 if quote_data.get('main_rental_item') else 1
            for i, item in enumerate(quote_data['service_line_items'], start=start_index):
                main_items_html += f'<tr><td style="font-size: 120%;"><b>{i}</b></td><td style="font-size: 120%;">{item.get("line_description", "")}</td><td style="font-size: 120%; text-align: right;">{item.get("qty", 1)}</td><td style="font-size: 120%; text-align: right;">{item.get("unit_price", 0.0):,.2f}</td></tr>'
        if quote_data.get('security_deposit', 0) > 0:
            last_index = len(quote_data.get('service_line_items', [])) + (1 if quote_data.get('main_rental_item') else 0) + 1
            main_items_html += f'<tr><td style="font-size: 120%;"><b>{last_index}</b></td><td style="font-size: 120%;">Deposit</td><td style="text-align: right; font-size: 120%;">1</td><td style="text-align: right; font-size: 120%;">{quote_data.get("security_deposit", 0.0):,.2f}</td></tr>'
    else: # For sales and refurbish
        if quote_data.get('line_items'):
            for i, item in enumerate(quote_data['line_items'], start=1):
                main_items_html += f'<tr><td style="font-size: 120%;"><b>{i}</b></td><td style="font-size: 120%;">{item.get("line_description", "")}</td><td style="font-size: 120%; text-align: right;">{item.get("qty", 1)}</td><td style="font-size: 120%; text-align: right;">{item.get("unit_price", 0.0) * item.get("qty", 1):,.2f}</td></tr>'
    quote_data['main_items_html'] = main_items_html

    # --- Equipment Provided Box (Rental Only) ---
    equipment_html = ""
    if doc_type == 'rental' and quote_data.get('selected_equipment'):
        equipment = quote_data['selected_equipment']
        half_point = (len(equipment) + 1) // 2
        left_col = equipment[:half_point]
        right_col = equipment[half_point:]
        equipment_html += '<div class="details-box" style="margin-top: 20px; font-size: 110%;"><h4 style="margin-top: 0; margin-bottom: 5px;">Equipment & Service Provided</h4>'
        equipment_html += '<table style="width: 100%; border: 0;"><tr style="vertical-align: top;">'
        equipment_html += '<td style="width: 50%; padding-right: 5px; border: 0;"><ul>'
        for item in left_col:
            equipment_html += f'<li>{item}</li>'
        equipment_html += '</ul></td><td style="width: 50%; padding-left: 5px; border: 0;"><ul>'
        for item in right_col:
            equipment_html += f'<li>{item}</li>'
        equipment_html += '</ul></td></tr></table></div>'
    quote_data['equipment_html'] = equipment_html
    
    # --- Description Heading ---
    description_heading = ""
    if doc_type == 'rental':
        description_heading = '<th style="width: 65%; font-size: 120%;"><strong>Rental Package Details</strong></th>'
    else:
        description_heading = '<th style="width: 65%; font-size: 120%;"><strong>Description</strong></th>'
    quote_data['description_heading'] = description_heading
    
    # --- Header Content ---
    header_content_html = ""
    
    # --- Top Section ---
    top_section_html = '<table style="width: 100%; border: 0; vertical-align: middle;"><tr>'
    
    # Left Column: Logo and Name/SSM (side-by-side with no gap)
    left_col_top = '<td style="width: 60%; border: 0;">'
    left_col_top += '<table style="width: 100%; border: 0; vertical-align: middle;"><tr>'
    if quote_data.get('issuing_company_logo'):
        left_col_top += f'<td style="border: 0; padding: 0; vertical-align: middle;"><img src="{quote_data["issuing_company_logo"]}" style="max-width: 150px; max-height: 90px; display: block;"></td>'
        left_col_top += '<td style="border: 0; padding: 0; vertical-align: middle;">'
    else:
        left_col_top += '<td style="border: 0; padding: 0; vertical-align: middle;">'
    left_col_top += f'<h2 style="margin: 0; font-size: 28px;">{quote_data.get("issuing_company", "")}</h2>'
    if quote_data.get('issuing_company_ssm_no'):
        left_col_top += f'<p style="margin: 0; font-size: 10px;">({quote_data["issuing_company_ssm_no"]})</p>'
    left_col_top += '</td></tr></table></td>'
    
    # Right Column: Company Address
    company_address_formatted = quote_data.get("issuing_company_address", "").replace('\n', '<br>')
    right_col_top = f'<td style="width: 40%; border: 0; text-align: right; font-size: 13px; vertical-align: middle;">{company_address_formatted}</td>'
    
    top_section_html += left_col_top + right_col_top + '</tr></table>'
    header_content_html += top_section_html
    header_content_html += '<hr style="border: 0; border-top: 1px solid #333; margin: 15px 0;">'

    # --- Second Section ---
    cust_name = quote_data.get('cust_name', '')
    company_address = quote_data.get('company_address', '')
    if company_address and '\n' not in company_address: # Wrap long single-line addresses
        company_address = textwrap.fill(company_address, width=35)
    company_address_html = company_address.replace('\n', '<br>') if company_address else ''
    cust_contact = quote_data.get('cust_contact', '')
    salesperson = quote_data.get('salesperson', '')
    customer_details_html = f"<strong>To:</strong><br>{cust_name}<br>{company_address_html}<br>Contact: {cust_contact}<br>Salesperson: {salesperson}"
    
    document_title = quote_data.get('document_title', '')
    doc_no = quote_data.get('doc_no', '')
    date = quote_data.get('date', '')
    title_block_html = f'<h1 style="margin: 0; font-size: 22px;">{document_title}</h1><table style="width: 100%; text-align: left; margin-top: 10px; font-size: 12px; border: 0;"><tr><td style="border: 0; padding: 3px;"><strong>Quote No.:</strong></td><td style="border: 0; padding: 3px;">{doc_no}</td></tr><tr><td style="border: 0; padding: 3px;"><strong>Date:</strong></td><td style="border: 0; padding: 3px;">{date}</td></tr></table>'
    
    second_section_html = '<table style="width: 100%; vertical-align: top; font-size: 12px; margin-bottom: 20px; border: 0;"><tr>'
    second_section_html += f'<td style="width: 40%; border: 0; word-wrap: break-word; white-space: normal;">{customer_details_html}</td>'
    second_section_html += '<td style="width: 20%; border: 0;"></td>' # Empty middle column
    second_section_html += f'<td style="width: 40%; text-align: left; border: 0; padding-left: 20px;">{title_block_html}</td>'
    second_section_html += '</tr></table>'
    header_content_html += second_section_html

    # --- Vehicle Details Box ---
    truck_number = quote_data.get('truck_number', '')
    body = quote_data.get('body', '')
    contract_period = quote_data.get('contract_period', 'N/A')
    vehicle_details_right_col = ""
    if doc_type in ['sales', 'refurbish']:
        vehicle_details_right_col = f"<strong>Body:</strong> {body}"
    elif doc_type == 'rental' and quote_data.get('rental_period_type') == 'monthly':
        vehicle_details_right_col = f"<strong>Contract Period:</strong> {contract_period}"
    header_content_html += f'<div class="details-box" style="font-size: 12px; margin-bottom: 20px;"><table style="width: 100%; border: 0;"><tr><td style="border: 0; padding: 2px; width: 50%;"><strong>Lorry No:</strong> {truck_number}</td><td style="border: 0; padding: 2px; width: 50%;">{vehicle_details_right_col}</td></tr></table></div>'
    
    quote_data['header_content_html'] = header_content_html
    
    return quote_data

def _render_html_template(context, template_file):
    """Renders a Jinja2 template."""
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), auto_reload=True)
    template = env.get_template(template_file)
    return template.render(**context)

def _convert_html_to_pdf(html_content, extra_options=None):
    """Sends HTML to Gotenberg for conversion."""
    files = {"files": ("index.html", html_content.encode("utf-8"))}
    form_data = {'omitBackground': (None, 'true'), 'printBackground': (None, 'true')}
    if extra_options:
        for key, value in extra_options.items():
            form_data[key] = (None, str(value))
    
    try:
        response = requests.post(GOTENBERG_API_URL, files=files, data=form_data, timeout=30)
        response.raise_for_status()
        return response.content
    except requests.exceptions.RequestException as e:
        pdf_generator_logger.error(f"Failed to connect to Gotenberg API: {e}", exc_info=True)
        raise

def _stamp_and_paginate(content_pdf_bytes, header_pdf_bytes, footer_pdf_bytes):
    """
    Stamps a header and footer onto every page of the main content PDF and adds page numbers.
    """
    writer = PdfWriter()
    content_pdf = PdfReader(io.BytesIO(content_pdf_bytes))
    header_page = PdfReader(io.BytesIO(header_pdf_bytes)).pages[0]
    footer_page = PdfReader(io.BytesIO(footer_pdf_bytes)).pages[0]
    
    num_pages = len(content_pdf.pages)

    for i, page in enumerate(content_pdf.pages):
        packet = io.BytesIO()
        can = canvas.Canvas(packet, pagesize=A4)
        page_num_text = f"Page {i + 1} of {num_pages}"
        
        page_width, _ = A4
        can.setFont("Helvetica", 9)
        can.drawString(page_width - 20 * mm, 15 * mm, page_num_text)
        can.save()
        packet.seek(0)
        
        num_page = PdfReader(packet).pages[0]

        page.merge_page(header_page)
        page.merge_page(footer_page)
        page.merge_page(num_page)
        writer.add_page(page)

    output_pdf_stream = io.BytesIO()
    writer.write(output_pdf_stream)
    return output_pdf_stream.getvalue()

def _save_pdf(pdf_bytes, doc_no):
    """Saves the final PDF to the export directory."""
    if not os.path.exists(EXPORT_DIR):
        os.makedirs(EXPORT_DIR)
    
    # Sanitize the document number to create a safe filename
    # Remove any characters that are not alphanumeric, dash, dot, or underscore
    safe_filename = re.sub(r'[^a-zA-Z0-9_.-]', '_', str(doc_no))
    file_path = os.path.join(EXPORT_DIR, f"{safe_filename}.pdf")

    try:
        with open(file_path, "wb") as f:
            f.write(pdf_bytes)
        pdf_generator_logger.info(f"Successfully generated PDF: {file_path}")
        return file_path
    except IOError as e:
        pdf_generator_logger.error(f"Error saving PDF file: {e}", exc_info=True)
        return None