# bot/constants.py

# Conversation states
(
    START,
    AWAITING_DOC_TYPE,
    AWAITING_INFO,
    REVIEWING_EXTRACTED_DATA,
    CONFIRMING_DETAILS,
    WAITING_FOR_COMPANY,
    SELECTING_SERVICES,
    WAITING_FOR_PRICE,
    ASK_FOR_PAYMENT_PHASES,
    COLLECTING_PHASE_AMOUNT,
    AWAITING_PAYMENT_PHASE_REMARKS,
    POST_GENERATION,
    SELECTING_FIELD_TO_EDIT,
    EDITING_FIELD,
    AWAITING_ADD_NEW_DETAIL_TYPE,
    WAITING_FOR_LORRY_PRICE,
    SELECTING_LORRY_SALE_TYPE,
    EDITING_LORRY_PRICE,
    START_RENTAL_FLOW,
    WAITING_FOR_RENTAL_PERIOD,
    WAITING_FOR_RENTAL_START_DATE,
    WAITING_FOR_RENTAL_END_DATE,
    WAITING_FOR_CONTRACT_PERIOD,
    WAITING_FOR_ROAD_TAX_PRICE,
    WAITING_FOR_INSURANCE_PRICE,
    WAITING_FOR_STICKER_PRICE,
    SELECTING_EQUIPMENT,
    WAITING_FOR_CUSTOM_SERVICE_NAME,
    AWAITING_COMPANY_NAME_CONFIRMATION,
    SELECTING_ITEM_TO_REMOVE,
    WAITING_FOR_AGREEMENT_PRICE,  # New state for agreement fee
    EDIT_MAIN_LINE_ITEMS,  # New state for editing main line items
    EDIT_SERVICE_LINE_ITEMS,  # New state for editing service line items
    EDITING_SERVICE_PRICE,
    SELECTING_MAIN_SERVICE,
    SELECTING_SUB_SERVICE,
    AWAITING_SUB_SERVICE_PRICE,
    SELECTING_BODY_WORK,
    SELECTING_BODY_WORK_SUB,
    SELECTING_ADDITIONAL_SERVICES,
    AWAITING_CUSTOM_ADDITIONAL_SERVICE_NAME,
    AWAITING_ADDITIONAL_SERVICE_PRICE,
    SELECTING_PAYMENT_PHASE_TO_EDIT,
    EDITING_PAYMENT_PHASE_AMOUNT,
    EDITING_PAYMENT_PHASE_REMARKS,
    REVIEWING_LINE_ITEMS,
    WAITING_FOR_CUSTOM_EQUIPMENT,
    SELECTING_ADDITIONAL_CATEGORY,
    SELECTING_ADDITIONAL_SUB_SERVICE,
) = range(49)

# Pre-defined lists
EQUIPMENT_LIST = [
    "Cabinet (Left)",
    "Cabinet (Right)",
    "Water Tank",
    "Sink",
    "Generator",
    "Deep Fryer",
    "Griller",
    "Chiller",
    "Initial Service",
    "LED Lightings",
    "Plug Points",
]

DEFAULT_RENTAL_EQUIPMENT = ["LED Lightings", "Initial Service", "Plug Points"]
